export interface EventDedupeOptions {
  ttlMs?: number;
  maxEntries?: number;
  rateLimitWindowMs?: number;
}

export interface EchoCheckInput {
  actorUserId?: number;
  groupId: number;
  type: string;
}

export class EventDeduplicator {
  private readonly seenEventTimestamps = new Map<string, number>();
  private readonly peerActionTimestamps = new Map<number, number[]>();
  private readonly ttlMs: number;
  private readonly maxEntries: number;
  private readonly rateLimitWindowMs: number;

  constructor(options?: EventDedupeOptions) {
    this.ttlMs = options?.ttlMs ?? 10 * 60 * 1000; // 10 minutes default
    this.maxEntries = options?.maxEntries ?? 10_000;
    this.rateLimitWindowMs = options?.rateLimitWindowMs ?? 60 * 60 * 1000; // 1 hour default
  }

  public isDuplicate(eventId: string): boolean {
    const now = Date.now();
    this.pruneOldEvents(now);

    if (this.seenEventTimestamps.has(eventId)) {
      return true;
    }

    // ponytail: capped Map size, fifo drop if over maxEntries
    if (this.seenEventTimestamps.size >= this.maxEntries) {
      const oldestKey = this.seenEventTimestamps.keys().next().value;
      if (oldestKey !== undefined) {
        this.seenEventTimestamps.delete(oldestKey);
      }
    }

    this.seenEventTimestamps.set(eventId, now);
    return false;
  }

  public isCommunityEcho(input: EchoCheckInput): boolean {
    // 1. Explicit outgoing event types generated by community admins or bot itself
    if (input.type === "message_reply" || input.type === "wall_reply_restore") {
      return true;
    }

    // 2. In VK, messages from community have from_id = -group_id
    if (typeof input.actorUserId === "number" && input.actorUserId === -Math.abs(input.groupId)) {
      return true;
    }

    return false;
  }

  public checkRateLimit(peerId: number, maxAllowedPerWindow: number): boolean {
    const now = Date.now();
    const history = this.getCleanPeerHistory(peerId, now);
    return history.length < maxAllowedPerWindow;
  }

  public recordAction(peerId: number): void {
    const now = Date.now();
    const history = this.getCleanPeerHistory(peerId, now);
    history.push(now);
    this.peerActionTimestamps.set(peerId, history);
  }

  private getCleanPeerHistory(peerId: number, now: number): number[] {
    const cutoff = now - this.rateLimitWindowMs;
    const existing = this.peerActionTimestamps.get(peerId) ?? [];
    const valid = existing.filter((ts) => ts >= cutoff);
    this.peerActionTimestamps.set(peerId, valid);
    return valid;
  }

  private pruneOldEvents(now: number): void {
    const cutoff = now - this.ttlMs;
    for (const [key, ts] of this.seenEventTimestamps.entries()) {
      if (ts < cutoff) {
        this.seenEventTimestamps.delete(key);
      } else {
        // Map iterates in insertion order, can stop early
        break;
      }
    }
  }
}
